### ISSUE TITLE
[Request] Linux ARM port and Android Port on all Pangea games

### ISSUE THREAD

**Issue by Smashman4** [jorio/MightyMike#4] opened 2021-04-23 19:37 UTC
Would love to see all three of the Pangea games you ported on my RG351P and my GPD XD plus. Any chance that is possible for you? If not, how would I go about porting it to ARM and android with Pomme?

**Comment by jorio** [comment] 2021-04-24 08:48
Mighty Mike is a fairly simple SDL2 game, so it shouldn't be too difficult. The other games (especially Bugdom) are more involved, so I recommend starting with Mighty Mike.

I'd suggest investigating the build setup for an SDL2 sample app for Android first. Then, see if you can adapt Mighty Mike to that setup.

The only issue with an Android port I can think of for now is the way the game deals with its asset files — we're most likely going to need to rework that for Android.

**Comment by Smashman4** [comment] 2021-04-24 14:28
Oh ok. Android might be out of scope for me then. I'm a beginner when it comes to these things so I'd probably be awful at it. What about an ARM Linux port? Is there a way I can get a box86 wrapper for it, or would the port be similar to android?

Also, this is not related, but what about a Gridz port? It's the only other game I've been wanting to play besides these Pangea games.

**Comment by jorio** [comment] 2021-04-24 20:50
If SDL2 exists for the RG351P, then it should be easy to compile Mighty Mike for that system.

By the way, I just looked up the specs of the RG351P; its screen resolution is 480x320. Mighty Mike was designed for 640x480, so I'm not sure that screen will do it justice.

---

As for Gridz, I'm not familiar with that game. I make these ports as a hobby, out of love for the original games, so I'm only interested in porting games that I really appreciate ;)

That being said, if a porting effort emerges for that game, or other Mac games of the era, then I'd be happy to assist in using/improving Pomme, or to share advice that I've gained from making the Pangea ports.

**Comment by Smashman4** [comment] 2021-04-24 20:59
Yea SDL2 does exist for the 351P. So I just need to figure out how to compile for ARM and test it from there. There are certain devices that use the same chipset and architecture as the RG351P that use 640x480 resolution, so I could use those instead.

It's ok if you don't want to do Gridz. I could try porting it, but I couldn't compile Pomme on my macbook. is there any binary you can release for macs?

**Comment by jorio** [comment] 2021-04-24 21:29
Pomme isn't a standalone program that runs old Mac binaries on newer systems. It's a library meant to be linked against the original source code of a classic Mac program. So, you need Gridz's source code to be able to start working on a port. Is it available publicly, or have you obtained it from the author?

If you have Gridz's source code, then I suggest to start with [setting up your dev environment to build Mighty Mike](https://github.com/jorio/MightyMike/blob/master/BUILD.md). It's a good starting point because Mighty Mike embeds Pomme, so if you can compile Mike, it means you can compile Pomme too.

Then, once you've gotten Mighty Mike to build, you can adapt CMakeLists.txt and swap Mike's source code with Gridz's, and start porting ;)

**Comment by Smashman4** [comment] 2021-04-24 21:52
I see, thank you so much for your help. While I don't have the source code, I will try to request it via an email.

Also for the Linux ARM port, do I need to change any parameters before compiling for ARM?

**Comment by foote-darrell** [comment] 2021-04-28 05:21
Would you be able to remaster _Weekend Warrior?_ In full resolution and framerate?

**Comment by jpenguin** [comment] 2021-04-28 23:47
Untested, but AARCH64 AppImmage & Fedora ARM7
https://download.opensuse.org/repositories/home:/jpenguin/

**Comment by Smashman4** [comment] 2021-04-28 23:50
> Untested, but AARCH64 AppImmage & Fedora ARM7
> https://download.opensuse.org/repositories/home:/jpenguin/

Do you have it for Ubunbtu as well?

**Comment by jpenguin** [comment] 2021-04-28 23:56
I took a look at building a Debian package and said "Forget it."  AppImages should run anywhere though, 20.04 x86_64 worked for me

**Comment by Smashman4** [comment] 2021-04-28 23:59
> I took a look at building a Debian package and said "Forget it." AppImages should run anywhere though, 20.04 x86_64 worked for me

lol Ok. I'll test the AppImage later.

**Comment by Smashman4** [comment] 2021-04-29 01:09
> I took a look at building a Debian package and said "Forget it." AppImages should run anywhere though, 20.04 x86_64 worked for me

I just realized you don't have an AppImage 32 bit buld for ARM. can you make one?

**Comment by jpenguin** [comment] 2021-04-29 02:57
The OBS doesn't seem to have a template for Arm32 AppImages with the Leap 15.2 build environment that I'm using.  It might be possible, but it doesn't look like OBS supports it..  My spec & yml files are available in the devel branch of my fork, and I would welcome a debian rules file for deb creation.  Maybe you could use alien to convert my fedora arm7 rpm if you don't feel like compiling.  The Raspberry Pi 3/4 has an ARMv8 64 CPU, but most raspbian builds are still 32bit...

**Comment by jpenguin** [comment] 2021-05-11 23:30
Created from the Fedora armv7 rpm https://filedn.com/lHGef0SOQKnBTotcJeEfshJ/Games/Mighty%20Mike/Mighty_Mike-armhf.AppImage

completely untested

**Comment by jorio** [comment] 2023-01-28 20:37
Closing this issue because I now provide official Linux/ARM64 binaries as of [version 3.0.2](https://github.com/jorio/MightyMike/releases/tag/v3.0.2).

**Closed as completed by jorio** 2023-01-28 20:37 UTC
