### ISSUE TITLE
Game starts in a black screen

### ISSUE THREAD

**Issue by j4yn1ck5** [jorio/MightyMike#13] opened 2022-08-07 16:23 UTC
Windows 11, AMD x64 w/ Radeon 6700XT.

Sound works. I can navigate into an active game and hear events occurring. I can not get anything to display. I have tried compatibility modes, run as admin, enable direct play, windowed mode.

My brother apparently can run it on Windows 10, Intel/Nvidia with no issues.

**Comment by scrutinizer80** [comment] 2022-08-14 09:51
Same here.
Windows 11 x64, Nvidia RTX 3070

**Comment by jorio** [comment] 2022-08-14 10:53
You're using version 3.0.1, right?

Are you running into the same issue with [version 3.0.0](https://github.com/jorio/MightyMike/releases/tag/v3.0.0)? Some video initialization settings are different in this version.

Make sure to delete the prefs file when switching versions (`%APPDATA%\MightyMike\Prefs`). You don't have to delete your saved games and high scores.

**Comment by j4yn1ck5** [comment] 2022-08-14 14:44
I deleted everything including the Prefs file, and installed a new copy of Mighty Mike 3.0.0. The result is the same.

**Comment by scrutinizer80** [comment] 2022-08-28 09:48
Same black screen on a freshly installed latest version and the aforementioned version 3.0.0.

**Comment by jorio** [comment] 2022-08-28 13:24
Please try this build and let me know what the console window says: [MightyMike-3.0.1-debug1.zip](https://github.com/jorio/MightyMike/files/9439714/MightyMike-3.0.1-debug1.zip)

**Comment by scrutinizer80** [comment] 2022-09-03 07:37
> Please try this build and let me know what the console window says: [MightyMike-3.0.1-debug1.zip](https://github.com/jorio/MightyMike/files/9439714/MightyMike-3.0.1-debug1.zip)

The console says:
HW Concurrency = 32
INFO: Created renderer: direct3d

While there's a black window and the music is playing.

**Comment by jorio** [comment] 2022-09-03 08:58
@scrutinizer80 Any better luck with this new build? You'll get to pick which renderer to use. Please let me know which ones work for you and which ones don't.  [MightyMike-3.0.1-debug2.zip](https://github.com/jorio/MightyMike/files/9482264/MightyMike-3.0.1-debug2.zip)

**Comment by j4yn1ck5** [comment] 2022-09-03 14:20
Sorry for not getting back to you.

Debug 1 says:

HW Concurrency = 48
INFO: Created renderer: Direct3D
And then some stuff about my Switch Pro controller

(Still a black screen)

Debug 2: None of the included executables display any graphics. The generic Direct3D launcher included some error messages regarding a failure to get a vertex buffer.

**Comment by scrutinizer80** [comment] 2022-09-06 11:08
> Any better luck with this new build? You'll get to pick which renderer to use. Please let me know which ones work for you and >which ones don't.
@jorio 
Amazingly, None of them worked. :)

**Comment by jorio** [comment] 2022-09-08 21:42
OK, here's my final attempt to "blind fix" this without access to the hardware :)

This version bypasses SDL's 2D renderer and uses bare-bones OpenGL to display the game's framebuffer. I also threw in a build without high-DPI support, just in case that was the issue.

[MightyMike3.0.1-debug3.zip](https://github.com/jorio/MightyMike/files/9530775/MightyMike3.0.1-debug3.zip)

And if that still doesn't work... do any of my other Pangea ports work for you?

**Comment by j4yn1ck5** [comment] 2022-09-08 22:12
All of the executables from debug 3 have worked properly for me.

**Comment by scrutinizer80** [comment] 2022-09-11 18:18
@jorio 
> OK, here's my final attempt to "blind fix" this without access to the hardware :)

This time they all work!. :)

>And if that still doesn't work... do any of my other Pangea ports work for you?

Tried Bugdom, Cro-Mag, Otto-Matic. They all work flawlessly.

**Comment by scrutinizer80** [comment] 2023-01-27 21:51
Any hope for a permanent fix for this issue in the next release?

**Comment by jorio** [comment] 2023-01-27 22:16
Yes, I plan to migrate the game to the OpenGL renderer that worked for you — belated thanks for your feedback, by the way!

I just haven't gotten around to putting together a proper release yet. But I've been doing some maintenance on the other games lately, so I'll try to update Mike soon, too.

Will keep you posted here.

**Comment by jorio** [comment] 2023-01-28 20:24
Closing this issue because I just released [Mighty Mike 3.0.2](https://github.com/jorio/MightyMike/releases/tag/v3.0.2) which includes the new renderer.

Feel free to reopen the issue if you're still getting a black screen.

Have fun!

**Comment by scrutinizer80** [comment] 2023-02-05 20:17
This issue still exists in version 3.02.

(Bugdom 1.3.3 works flawlessly. What's so different about MightyMike?)

**Comment by scrutinizer80** [comment] 2023-02-05 20:21
@j4yn1ck5 Can you re-open this issue?
(assuming you encounter the same thing in v3.02 yet again)

**Comment by jorio** [comment] 2023-02-05 20:30
Reopening, but I don't understand what's going on. 3.0.2 is essentially a non-debug version of the build I sent you earlier.

Could it be fullscreen mode? The "debug3" build that worked for you started in a window if I recall correctly, but 3.0.2 starts fullscreen. @scrutinizer80, can you try pressing alt+enter to toggle fullscreen mode in 3.0.2? (If you want to try it in debug3, the key was F11 instead of alt+enter)

**Comment by j4yn1ck5** [comment] 2023-02-05 20:30
> @j4yn1ck5 Can you re-open this issue? (assuming you encounter the same thing in v3.02 yet again)

Yes. The fix does not appear to be reflected in v3.02. I'm also experiencing this issue again.

**Comment by j4yn1ck5** [comment] 2023-02-05 20:32
> Reopening, but I don't understand what's going on. 3.0.2 is essentially a non-debug version of the build I sent you earlier.
> 
> Could it be fullscreen mode? The "debug3" build that worked for you started in a window if I recall correctly, but 3.0.2 starts fullscreen. @scrutinizer80, can you try pressing alt+enter to toggle fullscreen mode in 3.0.2? (If you want to try it in debug3, the key was F11 instead of alt+enter)

Alt+Enter changes from fullscreen to windowed, but does not appear to fix the renderer.

**Comment by jorio** [comment] 2023-02-05 20:37
Do you mind trying this out?

Press Win+R, enter `%APPDATA%\MightyMike`, extract the Prefs file from 
[the attached zip](https://github.com/jorio/MightyMike/files/10612104/Prefs.zip) in that folder and see if that changes anything for 3.0.2.

This file sets all graphics settings to the minimum, if it works we can work up from there and find out what fails.

**Comment by j4yn1ck5** [comment] 2023-02-05 20:40
Does not appear to have fixed anything. But now it has informative numbers about the graphics settings in the title bar.

**Comment by jorio** [comment] 2023-02-05 21:22
Wait... I know what's going on. It's a dumb mistake on my part in the code. It wasn't the renderer's fault after all.

Your CPUs have 32 cores or more, right?

To post-process the framebuffer, the game tries to use as many threads as there are cores in the CPU, up to a limit of 32 threads. But it turns out the 32nd rendering thread would always hang, so the picture would never get drawn. I never ran into this issue because I never ran the game on such a beast of a CPU. But when I force the game to run on 32 threads, I'm seeing the same black screen as you guys.

Debug3 happened to work because I turned off multithreading in that specific build in order to make troubleshooting easier.

So let's test if my assumption is correct... Here's a build that is identical to 3.0.2, except that it fixes the issue with that 32nd thread. Try to drop this file in Mighty Mike 3.0.2's folder and run it: 
[MightyMike-32threadfix.zip](https://github.com/jorio/MightyMike/files/10613854/MightyMike-32threadfix.zip)

If that was it, then I'll roll the fix into 3.0.3 asap.

**Comment by j4yn1ck5** [comment] 2023-02-05 21:32
I do indeed. I guess I never mentioned that I run a Threadripper build. This fix worked.

**Comment by jorio** [comment] 2023-02-05 21:36
Great! Can you confirm that the title bar says "thr:32"?

(to get it to show debug information, enter Presentation Settings and enable Titlebar Debug)

**Comment by j4yn1ck5** [comment] 2023-02-05 21:43
Yes it does.

**Comment by j4yn1ck5** [comment] 2023-02-05 21:52
My processor is a TR 2970WX, 24-Core 48-Threads.

**Comment by jorio** [comment] 2023-02-05 22:48
Thanks for the info.

I released a ["hotfixed" v3.0.2 here](https://github.com/jorio/MightyMike/releases/tag/v3.0.2). If that works for both of you, we can close this :)

**Comment by j4yn1ck5** [comment] 2023-02-05 23:53
Yup. Works fine for me. Haven't heard from @scrutinizer80 yet.

**Comment by scrutinizer80** [comment] 2023-02-06 10:01
Sorry for being late to the party.
I can confirm the hotfixed version works on my end, and that I'm also using a multicore CPU, but only **16 cores** - AMD 3950X.

Congrats to you both :-)

p.s. - Is MightyMike the only one that was affected by this?

**Comment by jorio** [comment] 2023-02-06 19:40
Sorry, I said “cores” but I should have said CPU threads. The 3950X exposes 32 hardware threads, so the game spawns 32 software threads for rendering.

The other games are single-threaded (as far as rendering goes) so they aren’t affected.

I’m glad we found a clean fix eventually, thanks to both of you for your patience :)

**Closed as completed by jorio** 2023-02-06 19:40 UTC

**Comment by solovedlife** [comment] 2024-10-20 02:02
Can I download this on ipad?
